spring.application.name=ecommerce

##### Use in-memory H2 database (resets on restart)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=admin
# spring.datasource.password=admin
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ### Enable H2 Console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Work in-memory H2 (no MySQL required)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Optional: show SQL for debugging
# spring.jpa.show-sql=true

# Uncomment below to use H2 with 0 external dependency
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop


# spring.data.rest.base-path=/api
spring.security.user.name=admin
spring.security.user.password=12345omarshahd


jwt.secret=U3ByaW5nQm9vdFVzZXJTZWNyZXRLZXlWYWx1ZTEyMzQ1Ng==

#----- to use database from terminal-----
# mysql> USE springAmazonDb;
# mysql> show tables;
# mysql> select * from users;

#----- Rabbit MQ Config-----
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest