#create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: amazon-ecommerce
  labels:
    name: amazon-ecommerce
    
---
#Create Pods
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: amazon-deployment
  namespace: amazon-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
         - name: amazon-ecommerce
           image: ajkumar98/amazon-ecommerce:latest
           ports:
             - containerPort: 8070
           env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_HOST
              value: mongodb-service
            - name: MONGO_PORT
              value: "27017"
