apiVersion: v1
kind: Service
metadata:
  name: amazon-service-lb
  namespace: amazon-ecommerce
spec:
  type: LoadBalancer
  selector:
    app: amazon
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8070
