apiVersion: v1
kind: Service
metadata:
  name: amazon-service-nodeport
  namespace: amazon-ecommerce
spec:
  type: NodePort
  selector:
    app: amazon
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8070
    nodePort: 30080
